libp2p/jvm-libp2p

build.gradle.kts
src/main/kotlin/io/libp2p/core/crypto/PublicKey.kt
src/main/kotlin/io/libp2p/core/encode/Base58.kt
src/main/kotlin/io/libp2p/core/multiformats/Multiaddr.kt
src/main/kotlin/io/libp2p/core/multiformats/Multihash.kt
src/main/kotlin/io/libp2p/core/types/BufferExtensions.kt
src/main/kotlin/io/libp2p/core/types/Uvarint.kt
src/test/kotlin/io/libp2p/core/encode/Base58Test.kt
src/test/kotlin/io/libp2p/core/multiformats/MultihashTest.kt

Next up:
* crypto (public/private keys).
* peer ID.
* multiaddr.

add base58 and multihash

---

src/main/kotlin/io/libp2p/core/protocol/Negotiator.kt
src/main/kotlin/io/libp2p/core/util/netty/StringSuffixCodec.kt
src/test/kotlin/io/libp2p/core/security/secio/SecIoSecureChannelTest.kt

Address a couple of issues

---

src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
src/test/kotlin/io/libp2p/core/HostTest.kt
src/test/kotlin/io/libp2p/security/noise/NoiseSecureChannelTest.kt
src/test/kotlin/io/libp2p/spike/Spike.kt.ignore

Refactored HostTest to parameterise on secure channel type. 
Split monolithic test into three so we can consider each individually.

Refactored tests

---

README.md
build.gradle.kts
src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
src/test/java/io/libp2p/tools/p2pd/P2PDDht.java
src/test/java/io/libp2p/tools/p2pd/P2PDHost.java
src/test/java/io/libp2p/tools/p2pd/libp2pj/DHT.java
src/test/java/io/libp2p/tools/p2pd/libp2pj/Host.java
src/test/java/io/libp2p/tools/p2pd/libp2pj/PeerInfo.java
src/test/java/io/libp2p/tools/p2pd/libp2pj/Transport.java
src/test/java/io/libp2p/tools/p2pd/libp2pj/util/Cid.java
src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt

Final release stuff: 
- readme update
- Artifact publishing 
- get rid of `multiformats` dependency
... anything missing?

Feature/release 0.1.0

---

src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
src/main/kotlin/io/libp2p/pubsub/flood/FloodRouter.kt
src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
src/test/kotlin/io/libp2p/pubsub/TestRouter.kt
src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt

Resolves #56 
Also a fix for gossipsub

Add Pubsub client validator API

---

src/main/kotlin/io/libp2p/etc/types/OtherExt.kt
src/test/kotlin/io/libp2p/etc/types/BooleanExtTest.kt

Fixes extension. Old code produced some misconception.

Fix boolean extension whenTrue + test

---

src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
src/main/kotlin/io/libp2p/security/secio/SecIoCodec.kt
src/main/kotlin/io/libp2p/security/secio/SecIoSecureChannel.kt

Rebasing PR #102 to the `0.3.x` branch

Reduce log levels for expected conditions.

---

src/main/kotlin/io/libp2p/etc/util/P2PService.kt
src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt

Catch and report internal pubsub exceptions.

---

src/main/kotlin/io/libp2p/etc/util/P2PService.kt
src/main/kotlin/io/libp2p/etc/util/P2PServiceSemiDuplex.kt
src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt

Fix gossip double connect

---

README.md
build.gradle.kts
src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
src/main/kotlin/io/libp2p/etc/util/netty/StringSuffixCodec.kt
src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
src/test/kotlin/io/libp2p/etc/util/netty/StringSuffixCodecTest.kt
src/test/kotlin/io/libp2p/pubsub/PubsubApiTest.kt

All changes from develop branch with version set to 0.5.4-RELEASE.

0.5.4 release

---

README.md
build.gradle.kts
src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
src/test/kotlin/io/libp2p/pubsub/gossip/GossipScoreTest.kt

Add `behaviourPenaltyThreshold` Gossip 1.1 param
This is not in official spec yet, but coming soon. 
The corresponding Go commit: https://github.com/libp2p/go-libp2p-pubsub/commit/b7c28b504da747004543e4d440dc80d6165d0f5b

Add behaviourPenaltyThreshold Gossip 1.1 param

---

README.md
build.gradle.kts

Fix https://github.com/quantstamp/teku/issues/28

Add build info to README.md

---

README.md
build.gradle.kts
src/main/kotlin/io/libp2p/etc/types/MutableBiMultiMap.kt
src/main/kotlin/io/libp2p/etc/util/P2PService.kt
src/main/kotlin/io/libp2p/pubsub/SeenCache.kt
src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
src/test/java/io/libp2p/pubsub/GossipApiTest.java
src/test/kotlin/io/libp2p/etc/types/MutableBiMultiMapTest.kt
src/test/kotlin/io/libp2p/pubsub/SeenCacheTest.kt

PRs in his release: 
- #164: Critical Gossip performance fixes

Release 0.6.2

---

README.md
build.gradle.kts
src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt

Fixes file handle leak by adding a timeout to NOISE handshakes.

0.8.3 release

---

build.gradle.kts

Update to log4j 2.17.0

---

.travis.yml
build.gradle.kts

Update dokka to work with latest gradle
Add dokka to CI to ensure it isn't broken in future.

Update dokka to work with latest gradle

---

build.gradle.kts
src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
src/main/kotlin/io/libp2p/transport/implementation/NettyTransport.kt
src/test/kotlin/io/libp2p/core/HostTest.kt
src/test/kotlin/io/libp2p/pubsub/gossip/Eth2GossipParams.kt
src/test/kotlin/io/libp2p/security/noise/NoiseHandshakeTest.kt
src/test/kotlin/io/libp2p/transport/NullConnectionUpgrader.kt

Updates dependencies: 
protobuf  2.19.2
kotlinx-coroutines-core 1.6.0
guava 31.0.1
bouncy castle 1.70
commons-codec 1.15
kotlin 1.6.10
kotlinter 3.8.0
mockk 1.12.2
mockito 4.2.0
assertj 3.22.0
Includes some Kotlin reformatting and method name changes required by the upgrades.

0.8.7 release

---

build.gradle.kts
src/main/kotlin/io/libp2p/core/multiformats/Multiaddr.kt
src/main/kotlin/io/libp2p/core/multiformats/MultiaddrDns.kt
src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt
src/main/kotlin/io/libp2p/host/HostImpl.kt
src/main/kotlin/io/libp2p/network/NetworkImpl.kt
src/main/kotlin/io/libp2p/security/SecureChannelError.kt
src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
src/test/java/io/libp2p/core/HostTestJava.java
src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt
src/test/kotlin/io/libp2p/pubsub/GoInteropTest.kt
src/test/kotlin/io/libp2p/pubsub/gossip/TwoGossipHostTestBase.kt
src/test/kotlin/io/libp2p/security/CipherSecureChannelTest.kt
src/test/kotlin/io/libp2p/security/SecureChannelTestBase.kt
src/test/kotlin/io/libp2p/security/plaintext/PlaintextInsecureChannelTest.kt
src/test/kotlin/io/libp2p/tools/TestChannel.kt

Includes refactoring of Multiaddr and PeerId checks on dial.

0.8.8 Release

---

README.md

Add JitPack to readme

---

libp2p/src/main/kotlin/io/libp2p/core/dsl/Builders.kt
libp2p/src/main/kotlin/io/libp2p/etc/util/netty/protobuf/LimitedProtobufVarint32FrameDecoder.kt
libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/builders/GossipRouterBuilder.kt
libp2p/src/main/kotlin/io/libp2p/transport/implementation/ConnectionOverNetty.kt
libp2p/src/main/kotlin/io/libp2p/transport/tcp/TcpTransport.kt

Add some more Gossip customization abilities for using in Gossip simulator

Open some Gossip members for hacking

---

libp2p/build.gradle.kts
libp2p/src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
tools/simulator/build.gradle
versions.gradle

Use Bouncycastle class instead

Remove Apache commons-codec dependency

---

README.md

Add Consensys and Jitpack repositories

Add all required repositories to the README

---

libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt

Revert changes in https://github.com/libp2p/jvm-libp2p/pull/318
Since it is a duplex stream and there is no notion of inbound/outbound and there is no possibility of 2 `MuxId` per stream, there is no need for a separate map.
- Created `WindowSize` data class to track both send and receive for a `MuxId`

[Yamux] Refactor window sizes retrieval

---

build.gradle.kts
libp2p/build.gradle.kts
libp2p/src/main/kotlin/io/libp2p/security/secio/SecIoCodec.kt
versions.gradle

Skipping upgrading `io.gitlab.arturbosch.detekt` because later versions are not compatible with the current version of Kotlin used.

Dependencies updates

---

funding.json

Update the funding.json to the correct project ID for the OP round 5 application

chore: Update funding.json
