libp2p/jvm-libp2p

- build.gradle.kts
- src/main/kotlin/io/libp2p/core/Host.kt
- src/main/kotlin/io/libp2p/core/multiformats/Multiaddr.kt
- src/main/kotlin/io/libp2p/core/multiformats/Multihash.kt
- src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
- src/main/kotlin/io/libp2p/core/types/ByteArrayExtensions.kt
- src/main/kotlin/io/libp2p/core/types/Uvarint.kt
- src/test/kotlin/io/libp2p/core/HostTest.kt
- src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt
- src/test/kotlin/io/libp2p/core/multiformats/ProtocolTest.kt
- src/test/kotlin/io/libp2p/core/types/UvariantTest.kt
There is still a dependency https://github.com/multiformats/java-multiaddr to address P2P protocol. 
Also there is a bug with `Base32.encode()` there which affects `ONION` protocol
Should we address those issues now or just create a couple of issues and leave it as is for now?
> Implement MultiAddr

- src/main/kotlin/io/libp2p/core/transport/tcp/TcpTransport.kt
- src/test/kotlin/io/libp2p/core/transport/tcp/TcpTransportTest.kt
I had a hard time falling asleep last night, so I decided to poke around at jvm-libp2p and find something simple to do 😄 
This implements `TcpTransport#handles` and adds a test for it.
> Tcp handles

- README.md
Changes `secp256k1?)ç` to `secp256k1)`.  I think these extra chars were some kind of unicode rendering problem, or else just a typo.
> Fixed minor text formatting error

- src/main/kotlin/io/libp2p/security/secio/SecioHandshake.kt
Move from SecureRandom.getStrongInstance() to SecureRandom()
On some Linux platforms (depending on underlying hardware), SecureRandom.getStrongInstance() will default to reading /dev/random. However, /dev/random can block for an indefinite time - I've
left for 12+hours. Switching to SecureRandom() will read from /dev/urandom, which doesn't block.
This is a long existing and well-known (once you know to look for it) behaviour, which nobody seems to think is sensible. See, for instance, this bug report https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6521844 which offers mitigation in the form of setting system parameters. The shorthand method of doing that is simply to use SecureRandom() instead (as the Bouncycastle libraries do, for example). There's also a good discussion here …
> Prevent Secio handshake from blocking on some platforms

- src/main/kotlin/io/libp2p/security/noise/NoiseXXCodec.kt
- src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
- src/test/kotlin/io/libp2p/security/noise/NoiseSecureChannelTest.kt
Several updates to #37:
- decompose Noise Cipher from Handshake classes to make classes code more clear
- avoid allocating max buffers for each message
- plain text should be binary
> Several updates to Noise PR

- README.md
- build.gradle.kts
- src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
- src/main/kotlin/io/libp2p/host/HostImpl.kt
- src/test/java/io/libp2p/tools/p2pd/P2PDDht.java
- src/test/java/io/libp2p/tools/p2pd/P2PDHost.java
- src/test/java/io/libp2p/tools/p2pd/libp2pj/DHT.java
- src/test/java/io/libp2p/tools/p2pd/libp2pj/Host.java
- src/test/java/io/libp2p/tools/p2pd/libp2pj/PeerInfo.java
- src/test/java/io/libp2p/tools/p2pd/libp2pj/Transport.java
- src/test/java/io/libp2p/tools/p2pd/libp2pj/util/Cid.java
- src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt
Resolves #51.
Resolves a bug found in HostImpl#removeConnectionHandler, where the function would attempt to add the passed handler to the connectionHandlers list, instead of attempting to remove the passed object from the list.
> Bugfix in HostImpl Connection Handler Logic

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
Fix gossip bug: the history is appended to the list tail and should be taken from the tail
> Simple gossip bug fix

- build.gradle.kts
- src/main/kotlin/io/libp2p/etc/util/netty/mux/MuxChannel.kt
- src/main/kotlin/io/libp2p/mux/MuxHandler.kt
- src/main/kotlin/io/libp2p/transport/implementation/ConnectionOverNetty.kt
- src/main/kotlin/io/libp2p/transport/implementation/P2PChannelOverNetty.kt
- src/main/kotlin/io/libp2p/transport/implementation/StreamOverNetty.kt
- src/test/kotlin/io/libp2p/pubsub/TestRouter.kt
The `Stream.isInitiator` is not the same as `Connection.isInitiator`
> Fix Stream.isInitiator

- src/main/kotlin/io/libp2p/etc/util/netty/AbstractChildChannel.kt
Rebasing #92 to the `0.3.x` branch
```
An exception was thrown by io.libp2p.etc.util.netty.AbstractChildChannel$1.operationComplete()
java.lang.IllegalStateException: channel not registered to an event loop
at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:163) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:127) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:856) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:467) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
at …
```
> Fix IllegalStateException

- src/test/java/io/libp2p/tools/schedulers/ControlledExecutorServiceImpl.java
- src/test/java/io/libp2p/tools/schedulers/TaskQueue.java
- src/test/java/io/libp2p/tools/schedulers/TimeController.java
- src/test/java/io/libp2p/tools/schedulers/TimeControllerImpl.java
We are having `FloodPubsubRouterTest.TenNeighboursTopology` intermittent failures on Travis. The failing is not reproducible locally. 
The case seemed even more mysterious taking into account that the test should be absolutely deterministic: 
- the whole network is executed on a single thread
- all randoms are determined with initial random seed  
It seems that the failing is caused by `StackOverflowException` since the current `ControlledExecutorService.execute()` invokes the submitted task 'in place' thus causing a pubsub message dissemination through the whole test peers network to be done on a single stack. 
Incrementing the number of test peers https://github.com/libp2p/jvm-libp2p/blob/9f741670cb27e55514768be1cce5c6d394e93cf5/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt#L222 …
> Fix intermittent Travis test failures 

- src/main/kotlin/io/libp2p/etc/util/netty/mux/AbstractMuxHandler.kt
- src/main/kotlin/io/libp2p/mux/MuxHandler.kt
- src/test/kotlin/io/libp2p/mux/MultiplexHandlerTest.kt
Handle AbstractMuxHandler exceptions since it's the last handler in connection pipeline. 
Log internal errors and unknown exceptions with WARN level
Partially addresses #101 issue.
> Fix muxer exception handling

- src/main/kotlin/io/libp2p/etc/util/netty/mux/MuxId.kt
- src/main/kotlin/io/libp2p/mux/MuxHandler.kt
- src/main/kotlin/io/libp2p/mux/mplex/MplexFrame.kt
- src/main/kotlin/io/libp2p/mux/mplex/MplexFrameCodec.kt
- src/test/kotlin/io/libp2p/mux/MultiplexHandlerTest.kt
When turning on muxer wire logs the _stream_ IDs should now look like: 
```
id=41c73d31/23/false
```
instead of 
```
MuxFrame(id=MuxId(id=20, initiator=false)
```
> Add parent channelId to the Muxer stream channelId for better wire logs grepping

- build.gradle.kts
- src/main/kotlin/io/libp2p/multistream/ProtocolSelect.kt
- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
- src/test/kotlin/io/libp2p/tools/ProtobufUtils.kt
- Ignore inbound messages without topics we are subscribed to. 
- Call notifyNonSubscribedMessage for potential penalty for the peer which is sending such messages
- Don't fail with exception if a message without subscribed topics still reaches Api class
- Add utility method for debugging protobuf related issues
Fixes https://github.com/PegaSysEng/teku/issues/2143
> Fix pubsub: ignore incoming messages we are not subscribed to

- src/main/kotlin/io/libp2p/etc/util/P2PService.kt
- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/transport/implementation/P2PChannelOverNetty.kt
- src/test/kotlin/io/libp2p/pubsub/MockRouter.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
Handle the issue: https://github.com/PegaSysEng/teku/issues/2288
It's not an exceptional situation in P2P when a malformed message received from a peer. So we shouldn't shout with `WARN` level in such situations, but just penalize the peer and `log.debug` the reason
> Fix pubsub malformed msg handling

- src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
This exposes the `peerTopics` variable via the public API which is useful for clients needing to evaluate how many peers are subscribed to particular topics.
Not entirely sure this is the right way to fit it into the APIs but think it is.  The big downside is that internally topics are tracked as `String` but the `PubsubSubscriberApi` wraps them in a `Topic` type.  That results in having to iterate through the data multiple times - once to copy the current state and once to wrap the `String` in `Topic`.
> Add method to API to retrieve complete list of subscribed topics by peer

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
Was getting the following exception on `GossipRouter.unsubscribe()`: 
```
java.util.ConcurrentModificationException: null
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:?]
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741) ~[?:?]
at io.libp2p.pubsub.gossip.GossipRouter.unsubscribe(GossipRouter.kt:607) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$unsubscribe$1.invoke(AbstractRouter.kt:292) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$unsubscribe$1.invoke(AbstractRouter.kt:34) ~[jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:212) [jvm-libp2p-minimal-0.6.0-RELEASE.jar:?]
at …
```
> Fix gossip unsubscribe

- build.gradle.kts
- src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
- src/main/kotlin/io/libp2p/etc/util/P2PService.kt
- src/main/kotlin/io/libp2p/etc/util/P2PServiceSemiDuplex.kt
- src/main/kotlin/io/libp2p/etc/util/netty/AbstractChildChannel.kt
- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/security/noise/NoiseXXCodec.kt
- src/main/kotlin/io/libp2p/transport/implementation/P2PChannelOverNetty.kt
- src/test/kotlin/io/libp2p/pubsub/MockRouter.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
New pubsub API feature:
- https://github.com/libp2p/jvm-libp2p/pull/118: Add method to API to retrieve complete list of subscribed topics by peer
The following issues were fixed: 
- #116: Fix pubsub malformed msg handling
- #117: Catch and report internal pubsub exceptions.
- #120: Fix gossip unsubscribe
- 7030249a: Remove listener from parent channel (Connection) on closing child channel (Stream) to avoid leaking Stream instances. Fixes https://github.com/PegaSysEng/teku/issues/2286
- 98a72bdf: Remove obsolete logging. Fix https://github.com/PegaSysEng/teku/issues/2268
- #124 'Duplicate stream for peer' exceptions
- https://github.com/libp2p/jvm-libp2p/pull/121/commits/d1b96c132665e33e879d7fc263787ef0d06310f7 CompletableFuture instance leaking
> Release 0.5.3

- src/main/kotlin/io/libp2p/etc/util/netty/StringSuffixCodec.kt
- src/test/kotlin/io/libp2p/etc/util/netty/StringSuffixCodecTest.kt
Multistream messages must end with `\n` so treat messages that don't as invalid.
Also only strip a single `\n` character from the end of the message.
> Throw exception when multistream messages do not end with line ending

- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
In `AbstractRouter` seenMessages is an LRU map so it automatically removes items when new ones are added to stay below some maximum size. So we could wind up with a message in msgSubscribed which is present in seenMessages when we first create msgUnseen but is then evicted when we we add the unseen messages on the second line. Then when we get to the last line seenMessages[getMessageId(it)] returns null because the message has now been dropped from seenMessages.
To avoid this, retrieve the value from `seenMessages` once and hold on to it while processing.  This avoids the risk that the value is dropped while recording the newly seen messages.
A less invasive change would be to move the line:
```
msgUnseen.forEach { seenMessages[getMessageId(it)] = Optional.empty() }
```
down below the …
> Retrieve the value from seenMessages once to avoid NullPointerException

- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
Reduce log level from INFO to DEBUG on inbound invalid gossip message
Should fix: https://github.com/PegaSysEng/teku/issues/2439
> Reduce log level from INFO to DEBUG on inbound invalid gossip message

- src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubApiTest.kt
Primarily address this issue https://github.com/ethereum/eth2.0-specs/issues/1981
- Make `seqId` field optional
- Allow omitting sender private key (and thus signature) 
- Allow custom `sender` and `seqId` fields per message 
Fix https://github.com/PegaSysEng/teku/issues/2476
> More flexible pubsub message fields handling

- src/main/kotlin/io/libp2p/etc/util/P2PServiceSemiDuplex.kt
If the stream was aborted during init, a peerHandler may never be assigned.  Need to handle that case in `P2PServiceSemiDuplex.streamActive`.  The superclass performs the same check but it must happen before calling `stream.getPeerHandler` to avoid exceptions.
fixes https://github.com/PegaSysEng/teku/issues/2359
> Check if the stream was closed on init

- src/main/kotlin/io/libp2p/core/Libp2pException.kt
- src/main/kotlin/io/libp2p/etc/types/AsyncExt.kt
- src/main/kotlin/io/libp2p/etc/util/P2PServiceSemiDuplex.kt
- src/main/kotlin/io/libp2p/pubsub/Errors.kt
- src/test/kotlin/io/libp2p/etc/types/AsyncExtTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/tools/TestLogAppender.kt
- Fix CompletableFuture anyComplete() implementation
- Tolerate the case when trying writing to a peer without established outbound stream within P2PServiceSemiDuplex
Resolves https://github.com/PegaSysEng/teku/issues/2620
> Fix the panic when SemiDuplex has no outbound stream yet

- src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubApiImpl.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubApiTest.kt
`from`, `seqNo` and `signature` are all optional fields.  On parsing they are allowed to be optional, but for `from` and `seqNo` previously the parsed message would set them to default values and when the messages were regossiped, the default values became explicitly set.  This caused the regossiped messages to be rejected by Lighthouse's stricter gossip 1.1 validation.
This does result in a public API change as from and seqId are now optional.  Additionally to enable testing, the seqIdGenerator can now return a null sequence number allowing the generation of messages with no sequence number.
> Do not set omitted fields to default values when regossiping

- README.md
- build.gradle.kts
- src/main/kotlin/io/libp2p/core/Stream.kt
- src/main/kotlin/io/libp2p/etc/util/netty/mux/MuxChannel.kt
- src/main/kotlin/io/libp2p/protocol/Identify.kt
- src/main/kotlin/io/libp2p/transport/implementation/StreamOverNetty.kt
- src/test/kotlin/io/libp2p/tools/TestStream.kt
`Identify` protocol should `CLOSE` the stream after writing the data instead of `RESET`
Fixes https://github.com/PegaSysEng/teku/issues/2728
> Fix Identify protocol stream close

- .travis.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Adds support for JDK 14
Upgrade google protobuf plugin for compatibility with new gradle
Remove buildscan plugin as it is now only available in gradle enterprise.
> Upgrade gradle to 6.6.1

- README.md
- build.gradle.kts
- src/main/java/io/libp2p/discovery/mdns/ServiceInfo.java
- src/main/java/io/libp2p/discovery/mdns/impl/DNSRecord.java
- src/main/java/io/libp2p/discovery/mdns/impl/JmDNSImpl.java
- src/main/java/io/libp2p/discovery/mdns/impl/ServiceInfoImpl.java
This PR addresses minor QuantStamp libp2p-related issues: 
- https://github.com/quantstamp/teku/issues/27: Clone method does not copy entire state 
- https://github.com/quantstamp/teku/issues/30: Clone May Return `null`
- https://github.com/quantstamp/teku/issues/29: Ignored `InterruptedException`
- (parttially) https://github.com/quantstamp/teku/issues/15: Incorrect Custom Equality and Hash Functions
> Fix misc QuantStamp issues

- src/main/kotlin/io/libp2p/etc/types/OtherExt.kt
- src/main/kotlin/io/libp2p/security/SecureChannelError.kt
- src/main/kotlin/io/libp2p/security/noise/NoiseXXCodec.kt
- src/main/kotlin/io/libp2p/security/secio/SecIoCodec.kt
- src/test/kotlin/io/libp2p/security/CipherSecureChannelTest.kt
- src/test/kotlin/io/libp2p/security/SecureChannelTest.kt
- src/test/kotlin/io/libp2p/security/noise/NoiseSecureChannelTest.kt
- src/test/kotlin/io/libp2p/security/secio/SecIoSecureChannelTest.kt
- src/test/kotlin/io/libp2p/tools/TestLogAppender.kt
We have failed to handle the case when `javax.crypto.AEADBadTagException` is the root cause of `CantDecryptInboundException`
Also `abruptlyClosing` flag was added to avoid nested decode exceptions during channel close. When channel is closing the netty `ByteToMessageDecoder` tries to feed all unprocessed bytes to the pipeline which again causes `CantDecryptInboundException` from security 'codec'. This makes sense when channel is closed remotely but should be prevented when we are closing the local channel abruptly
Fix when merged to Teku https://github.com/ConsenSys/teku/issues/3214
> Fix log ERROR when fail to decrypt inbound packet 

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
Addition to PR #136 : 
when the outbound Gossip stream is not created yet and remote Gossip peer (just connected) sends GRAFT to which we want respond with PRUNE causes exception (see https://github.com/ConsenSys/teku/issues/2836). 
This is because the `GossipRouter.enqueuePrune` needs the negotiated Gossip version to respond properly (Gossip v1.1 should be backward compatible with v1.0) and the version is retrieved from outbound stream. As the outbound stream can be not created yet the version can be retrieved from the inbound stream with the same result. One of inbound or outbound stream should 100% exist 
Fixes Teku issue https://github.com/ConsenSys/teku/issues/2836 when new version integrated
> Get negotiated Gossip protocol version from either inbound or outbound stream

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/builders/GossipPeerScoreParamsBuilder.kt
- src/test/kotlin/io/libp2p/pubsub/TestRouter.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/Eth2GossipParams.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
Fix the following scenario: 
- Node receives unseen `IHAVE` for message `M` from peer `P1`
- Node sends `IWANT M` to `P1`
- Node receives message `M` from peer `P2` notify the client and waits for its validation 
- While still in process of validation the `M` is received  from `P1` (as a response to `IWANT`)
- `notifyAnyValidMessage` is not called for the latter inbound and pending entry is not removed from `iWantRequests`
- Peer `P1` is penalized for `IWANT` response timeout 
The `iWantRequests` entry need to be cleared on any message. If a message occurs invalid the peer would be penalized in another way 
Also add the test verifying that a long period of Gossip `IGNORE` (i.e. not publishing any messages) doesn't underscore the node with Eth2 params
> Fix unfair IWANT penalty

- build.gradle.kts
- src/main/java/io/libp2p/discovery/mdns/impl/tasks/ServiceResolver.java
- src/main/kotlin/io/libp2p/protocol/Ping.kt
- src/test/kotlin/io/libp2p/security/SecureChannelTest.kt
- src/test/kotlin/io/libp2p/tools/TestChannel.kt
Fix 
- `SecureChannelTest` which periodically just hung the build: the reason was in using a regular `ArrayList` in multithreading scenario. Also discovered that channel methods were called from two threads: main and `TestChannel.executor`
- `HostTest.pingOverSecureConnection()` which periodically failed with non-expected exception: the reason was in unsynchronized `Ping` actions 
- Clean up build warnings
> Fix 2 flaky tests, clean up build 

- src/main/kotlin/io/libp2p/etc/util/netty/mux/AbstractMuxHandler.kt
Exceptions during decoding wind up being wrapped by netty in `DecoderException` so when deciding what level to use for exceptions, check the causal chain rather than just the outermost exception type.
See https://github.com/ConsenSys/teku/issues/3309 for an example of exceptions this would handle better.
> Check causal chain for exceptions when deciding what log level to use

- src/main/kotlin/io/libp2p/etc/types/Delegates.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/builders/GossipPeerScoreParamsBuilder.kt
- src/test/kotlin/io/libp2p/etc/types/DelegatesTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/Eth2GossipParams.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipScoreTest.kt
Update gossip scoring configuration API's:
* Expose setter for `GossipPeerScoreparamsBuilder.behaviourPenaltyThreshold`
* Add `Gossip.updateTopicScoreParams` to allow for topic scoring params to be updated after startup
> Tweak gossip scoring config apis

- README.md
- build.gradle.kts
Publish builds to cloudsmith instead of bintray.
Update instructions in README and add acknowledgement.
> Publish to CloudSmith

- src/main/kotlin/io/libp2p/etc/util/netty/mux/AbstractMuxHandler.kt
- src/test/kotlin/io/libp2p/mux/MultiplexHandlerTest.kt
It turned out that `readComplete` events are not propagated to child `Stream` channels and this caused `ReadTimeoutHandler` to behave incorrectly: it just didn't throw `TimeoutException` if at least one byte was read.
The idea is to propagate the `Connection` `readComplete` event to those `Streams` which were reading after the previous `readComplete` and are not yet closed.
> Fire readComplete() event to Stream channels

- README.md
- build.gradle.kts
- src/main/kotlin/io/libp2p/etc/util/netty/mux/AbstractMuxHandler.kt
- src/test/kotlin/io/libp2p/mux/MultiplexHandlerTest.kt
Includes the following changes:
* Releases are published to cloudsmith instead of bintray
* readComplete events are correctly propagated to Stream channels
> Release 0.8.0

- src/main/kotlin/io/libp2p/etc/types/Delegates.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/etc/types/DelegatesTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
On every inbound message `GossipRouter` checks the peer score against `graylistThreshold` to decide whether a message should be processed or ignored. 
The score calculation is not too cheap for extensive inbound message flow. 
The following optimizations were made: 
- Cache `PeerHandler.getIP()` 
- Cache topic score unless any of input values changed or time changed more than `timeInMeshQuantum`. Ideally that should be made on something like Rx `ObservableValue`s and `Bindings` to look nicer but that seems like an overkill for this change 
-  Maintain whitelist with expiration and message count for `acceptRequestsFrom` for peers with non-negative score to avoid score recalculation for every inbound message. The basic idea behind is that `graylistThreshold` should be far below `0` and if a …
> Optimize gossip score calculation

- README.md
- build.gradle.kts
- src/main/kotlin/io/libp2p/etc/types/Delegates.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/etc/types/DelegatesTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
Includes the following changes:
* Optimize gossip score calculations (#184)
> Release 0.8.1

- src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipScoreTest.kt
Added a method to retrieve peer score by peerId. This is needed for [making gossip scoring information visible to users](https://github.com/ConsenSys/teku/issues/3557).
> Add method to retrieve peer score by peerId

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipScoreTest.kt
Rework access to cached gossip score value.
> Safely access cached gossip score across threads

- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
- src/main/kotlin/io/libp2p/transport/implementation/ConnectionBuilder.kt
Addresses an issue where connections may leak if the secure channel or muxer establishment process stalls (e.g. because the remote peer doesn't respond). This is done using a rather basic timeout which appears to solve the issue but may not be the most elegant solution.  If the upgrade fails, the channel is closed to prevent the connection leaking.
At minimum we need to make the timeout configurable but it may be that this timeout should be pushed down into the individual handlers (eg `NoiseXXSecureChannel` and the actual muxing implementations).
> Add a timeout to the connection upgrade process

- src/main/kotlin/io/libp2p/pubsub/Errors.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
Throw specialized exception when no suitable peers to broadcast outbound exception. 
Currently an abstract `io.libp2p.etc.types.NothingToCompleteException` is thrown. 
The final intention is to get rid of noisy DEBUG logs with stacktrace in Teku client
> Throw specialized exception when no suitable peers to broadcast outbound exception

- README.md
This will keep the README's version up-to-date with the latest.
A few other clean-up items
- add syntax hints for the code blocks to make them pretty
- remove ">" from code blocks to make them copy/paste friendly
---
> Add version shield to README

- build.gradle.kts
- src/main/kotlin/io/libp2p/core/multistream/MultistreamProtocol.kt
- src/main/kotlin/io/libp2p/etc/util/netty/TotalTimeoutHandler.kt
- src/main/kotlin/io/libp2p/multistream/MultistreamImpl.kt
- src/main/kotlin/io/libp2p/multistream/MultistreamProtocolDebug.kt
- src/main/kotlin/io/libp2p/multistream/Negotiator.kt
- src/test/kotlin/io/libp2p/core/HostTranportsTest.kt
- src/test/kotlin/io/libp2p/multistream/MultistreamTest.kt
- src/test/kotlin/io/libp2p/security/SecureChannelTest.kt
- Limit the length of a single protocol id string to 1024
- Limit the total time spend for a protocol negotiation
> Improve multistream implementation 

- src/main/kotlin/io/libp2p/core/multiformats/Multiaddr.kt
- src/main/kotlin/io/libp2p/core/multiformats/MultiaddrDns.kt
- src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
- src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt
- src/main/kotlin/io/libp2p/host/HostImpl.kt
- src/main/kotlin/io/libp2p/network/NetworkImpl.kt
- src/main/kotlin/io/libp2p/security/SecureChannelError.kt
- src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
- src/test/java/io/libp2p/core/HostTestJava.java
- src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt
- src/test/kotlin/io/libp2p/pubsub/GoInteropTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/TwoGossipHostTestBase.kt
- src/test/kotlin/io/libp2p/security/CipherSecureChannelTest.kt
- src/test/kotlin/io/libp2p/security/SecureChannelTestBase.kt
- src/test/kotlin/io/libp2p/security/plaintext/PlaintextInsecureChannelTest.kt
- src/test/kotlin/io/libp2p/tools/TestChannel.kt
- Some `Multiaddr` class refactorings 
- Verify remote `PeerId` on connect
> Fix remote PeerId check on dial 

- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/test/kotlin/io/libp2p/pubsub/AbstractRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/SubscriptionsLimitTest.kt
Somewhat naive approach to ensuring created messages are within the message list limits.  Before adding each message part to the new message all list limits are checked. If limits would be exceeded the message part is re-added to the pending pool.
Some concerns:
1. Is it too expensive to perform these checks for every part we add?
2. Is it possible to deduplicate the checks in `validateMessageListLimits` (single message) and `validateMergedMessageListLimits` (two messages)?
3. Is there a better approach to handling parts that don't fit than just adding them back to the queue?
4. Will something actually trigger sending the remaining parts in a later message or do they get stuck?
5. How do we test this properly?
> Respect message list limits when creating messages to send

- src/test/kotlin/io/libp2p/transport/TransportTests.kt
There was a test that was failing on my laptop that was due to a timed sleep that was not long enough. Changing the wait to 20 seconds would fix the problem, but that makes the build slow for everyone. This will bail within a second of acknowledging all of the connections. If it hasn't acknowledged all of the connections within 30 seconds, the test will fail.
> Change hardcoded sleep to waiter pattern

- src/main/java/io/libp2p/discovery/mdns/impl/HostInfo.java
Simply rename all instances of this variable. Might have been a joke, but I think it's worth fixing.
> Rename variable "interfaze" -> "interface"

- src/main/kotlin/io/libp2p/core/Network.kt
- src/main/kotlin/io/libp2p/core/P2PChannel.kt
- src/main/kotlin/io/libp2p/core/PeerId.kt
- src/main/kotlin/io/libp2p/core/StreamHandler.kt
- src/main/kotlin/io/libp2p/core/crypto/Key.kt
- src/main/kotlin/io/libp2p/core/multiformats/Multihash.kt
- src/main/kotlin/io/libp2p/core/pubsub/PubsubApi.kt
- src/main/kotlin/io/libp2p/pubsub/Errors.kt
- src/main/kotlin/io/libp2p/pubsub/SeenCache.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
Two notable exceptions:
(1) Changed "unrecognized" to "unrecognised" because there are two other
instances of that word in the same file and this one stood out.
(2) Added equal sign to a few gossip param error messages. Other params that
accept zero for disabled values include "=" in the error message.
> Fix various typos

- build.gradle.kts
- src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt
- src/main/kotlin/io/libp2p/core/multiformats/Protocol.kt
- src/main/kotlin/io/libp2p/core/multistream/ProtocolBinding.kt
- src/main/kotlin/io/libp2p/core/mux/StreamMuxer.kt
- src/main/kotlin/io/libp2p/etc/encode/Base58.kt
- src/main/kotlin/io/libp2p/host/HostImpl.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
- src/main/kotlin/io/libp2p/pubsub/TopicSubscriptionFilter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/core/HostTest.kt
- src/test/kotlin/io/libp2p/core/multiformats/MultihashTest.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
- src/test/kotlin/io/libp2p/tools/NullHost.kt
- src/test/kotlin/io/libp2p/tools/TestChannel.kt
- src/test/kotlin/io/libp2p/tools/TestLogAppender.kt
- src/test/kotlin/io/libp2p/tools/protobuf/ProtobufUtils.kt
Fixed all of the build-time warnings for `compileKotlin` and `compileTestKotlin`. I tried to actually fix as much as I could, but everything else is just suppressed. For suppressed warnings, if there is a better way to handle these let me know.
For reference, here are the warnings I saw:
<details closed>
<summary>Task :compileKotlin</summary>
```
w: Language version 1.4 is deprecated and its support will be removed in a future version of Kotlin
w: jvm-libp2p/src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt: (19, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: jvm-libp2p/src/main/kotlin/io/libp2p/core/P2PChannelHandler.kt: (27, 6): 'JvmDefault' is deprecated. Switch to new -Xjvm-default modes: `all` or `all-compatibility`
w: …
```
> Fix build warnings

- src/main/kotlin/io/libp2p/etc/types/ByteArrayExt.kt
- src/main/kotlin/io/libp2p/etc/types/ByteBufExt.kt
- src/test/kotlin/io/libp2p/core/multiformats/MultiaddrTest.kt
- src/test/kotlin/io/libp2p/etc/types/UvarintTest.kt
When reading over code, I noticed that it was possible to provide a 10-byte
uvarint (variable length integer) instead of the 9-byte maximum. The functions
did not properly catch it.
Also, fix what I believe is a typo in the ByteArray version. It checked the
wrong variable (result vs index) which would almost always result in a null
value. Might as well throw an exception there like the other implementation.
Fixes #225.
> Forbid negative uvarint values

- src/test/kotlin/io/libp2p/etc/types/UvarintTest.kt
I added a duplicate test for round tripping encoding of a max long value.  Remove the duplicate.
> Remove duplicate test

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipParamsTest.kt
* For gossipFactor, there was a range mismatch.
* For graylistThreshold, the message said "gossipThreshold" instead.
* The others checked >= or <= but the message said > or <.
> Add GossipParam tests and fix a few small issues

- src/main/kotlin/io/libp2p/core/Network.kt
- src/main/kotlin/io/libp2p/core/transport/Transport.kt
- src/main/kotlin/io/libp2p/network/NetworkImpl.kt
- src/main/kotlin/io/libp2p/transport/implementation/ConnectionBuilder.kt
- src/main/kotlin/io/libp2p/transport/implementation/NettyTransport.kt
- src/test/java/io/libp2p/tools/schedulers/Scheduler.java
- src/test/kotlin/io/libp2p/pubsub/GoInteropTest.kt
- src/test/kotlin/io/libp2p/security/secio/EchoSampleTest.kt
- src/test/kotlin/io/libp2p/tools/NullTransport.kt
- src/test/kotlin/io/libp2p/transport/TransportTests.kt
This is more generic version of `DebugBuilder.beforeSecureHandler`: the raw channel pre-handler which could be specified per `listen()/dial()` call individually.
Add unit test for new `Transport` methods.
Also piggy tailing suppress unchecked warning for the test
> Add listen/dial `preHandler` optional parameter

- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
To make the hashCode collisions resistant, AbstractPubsubMessage uses sha256 as part of calculating the hashCode. That makes it fairly expensive and hashCode is intended to be very cheap. Reduce the number of sha256 calculations by caching the result.
> Cache pubsub message hashCode

- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
Rather than caching the hashCode itself, caches the sha256 of the message content and makes it available via an API.  This enables applications using custom seen caches to leverage the same cached sha256 value for collision resistant hashing without having to recalculate the sha256.
> Make cached sha256 of message data available

- detekt/baseline.xml
- src/main/kotlin/io/libp2p/core/crypto/Key.kt
- src/main/kotlin/io/libp2p/crypto/keys/Curve25519.kt
- src/main/kotlin/io/libp2p/crypto/keys/Ecdsa.kt
- src/main/kotlin/io/libp2p/crypto/keys/Ed25519.kt
- src/main/kotlin/io/libp2p/crypto/keys/Rsa.kt
- src/main/kotlin/io/libp2p/crypto/keys/Secp256k1.kt
This PR fixes the [EqualsWithHashCodeExist](https://detekt.dev/potential-bugs.html#equalswithhashcodeexist) according to what detekt says should be done in cases of inheritance.
> All hash-based collections depend on objects meeting the equals-contract. Two equal objects must produce the same hashcode. **When inheriting equals or hashcode, override the inherited and call the super method for clarification.**
Also added a default `Key.hashCode()` function.
> Fix detekt's EqualsWithHashCodeExist warnings

- gradle.properties
- src/main/kotlin/io/libp2p/crypto/keys/Secp256k1.kt
Currently `Secp256k1PrivateKey.sign()` instantiates `SecureRandom` on every call. 
It's obsolete, as BouncyCastle uses it's own `SecureRandom` singleton when not supplied one.
> Optimization: no need to instantiate SecureRandom on sign() calls

- src/main/kotlin/io/libp2p/etc/util/P2PService.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouterEventListener.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/DefaultGossipScoreTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
`GossipScore` consumes significant CPU time under high network load. 
This is initial refactoring before optimizations 
- Make `GossipRouter.score` property overridable 
- Extract 2 interfaces `GossipRouterEventListener` and `GossipScore`. Rename implementation to `DefaultGossipScore`
- Make them deal with `PeerId` instead of `PeerHandler`
- To retain the possibility to access `PeerHandler` add `P2PService:.peerIdToPeerHandlerMap`
- `P2PService`: hide mutable collections, expose immutable
> GossipScore refactor

- build.gradle.kts
- src/main/kotlin/io/libp2p/etc/util/P2PService.kt
- src/main/kotlin/io/libp2p/etc/util/P2PServiceSemiDuplex.kt
- src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
- src/main/kotlin/io/libp2p/pubsub/flood/FloodRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/builders/GossipRouterBuilder.kt
- src/test/java/io/libp2p/pubsub/GossipApiTest.java
- src/test/kotlin/io/libp2p/pubsub/DeterministicFuzz.kt
- src/test/kotlin/io/libp2p/pubsub/GoInteropTest.kt
- src/test/kotlin/io/libp2p/pubsub/MockRouter.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubApiTest.kt
- src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/TestRouter.kt
- src/test/kotlin/io/libp2p/pubsub/flood/FloodPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipBackwardCompatibilityTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipRouterListLimitsTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipRpcPartsQueueTest.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/TwoGossipHostTestBase.kt
This is follow up to #247 
In the very initial version I've made an attempt to invent a new Kotlin specific pattern which combines both builder and its resulting class entities. It should in theory make the code smaller and supporting efforts cheaper. 
But it finally failed to be both a builder pattern and any kind of sustainable code. With `GossipRouter` becoming more complex class that approach is turning into error-prone spaghetti code. 
This PR extracts `GossipRouterBuilder` with making `GossipRouter` properties final (where appropriate), which looks more like a traditional pattern for Teku code and should be less error-prone and more sustainable 
Also:
- Move property declarations right after primary constructor (which may also declare properties) in changed classes
- Refactor …
> Refactor GossipRouter: extract GossipRouterBuilder

- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouterEventListener.kt
- src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt
- src/test/kotlin/io/libp2p/pubsub/gossip/DefaultGossipScoreTest.kt
The current algorithm of IP colocation score calculation has `O(n^2)` complexity and consumes significant CPU with lots of peer connections
This PR:
- Modifies the algorithm to `O(n)` complexity 
- Extracts the `PeerIP` class (which could be adjusted to IPv6 and colocation criteria later) 
- Pass more specific `Multiaddr` type for the `onConnected()` event
> Optimizate GossipScore IP colocation calculation

- build.gradle.kts
Set the lib version to `develop` in the develop branch. 
This is for better local develop build testing. I.e. when you make `publishToMavenLocal` of a develop branch and need to test it with Teku of other project you may just use the `develop` maven dependency version
> Switch lib version to 'develop' in the develop branch

- src/main/kotlin/io/libp2p/etc/util/P2PService.kt
Attempt to fix an issue where `stream.getPeerHandler` is called even when steam is closed on initialization, which would always throw due to `peerHandler` not being set, as documented in `P2PService.closeAbruptly`
Avoiding the `stream.getPeerHandler` call in the case where `stream.aborted == true` should prevent this error.
Issue raised in Teku:
https://github.com/ConsenSys/teku/issues/6088
ps. I'm not familiar with the code base at all - so my investigation and guess may well be incorrect. I'm looking for a way to test this - any suggestions / ideas on how to do this is appreciated!
> Fix scenario where a call to `getPeerHandler` would always throw

- libp2p/build.gradle.kts
- tools/simulator/build.gradle
- versions.gradle
Follow up to https://github.com/libp2p/jvm-libp2p/issues/274#issuecomment-1549011067
'Umbrella' artifact `netty-all` transitively includes a lot of unneeded Netty dependencies. 
It's better to have finer grained Netty artifacts dependencies
> Finer grained netty dependencies

- libp2p/src/main/kotlin/io/libp2p/security/tls/TLSSecureChannel.kt
- libp2p/src/test/java/io/libp2p/core/HostTestJava.java
Also update unit test to cover this
Edit: Including another fix for early muxer negotiation via ALPN which wasn't actually using the ALPN result. 
Added a helper method to construct ECDSA based instances of TLS.
> Fix ecdsa cert usage in TLS which bouncycastle broke

- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/main/kotlin/io/libp2p/protocol/Ping.kt
- libp2p/src/test/java/io/libp2p/core/HostTestJava.java
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
Also fix inefficient window size handling.
I tried to test this with ping, but of course ping doesn't handle messages sent in multiple parts. But we have tested this downstream.
> Fix yamux handling of writes bigger than the window size

- libp2p/build.gradle.kts
https://docs.gradle.org/current/userguide/java_testing.html#ex-disable-publishing-of-test-fixtures-variants
> Disable publishing of test fixtures variants

- build.gradle.kts
- versions.gradle
Basically the generated pom will not have `<dependencyManagement>` section and versions will be resolved automatically by the publish plugin.
https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#pom-generation-disabling
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies
This results in a clean pom same as version 0.10.0 and below:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>io.libp2p</groupId>
<artifactId>jvm-libp2p</artifactId>
<version>develop</version> …
```
> Disable customization of the generated pom

- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
Mainly changes and refactoring around `SendBuffer` class. Also using a single `windowSizes` map for receive and send window sizes since the MuxId is different.
Before logic was checking the total written bytes in the buffer against the `sendWindow` to determine if it fits within window. That is not entirely correct since the sendWindow is changed inside `sendBlocks` method. That could lead to incorrect behaviour. 
Also there is a possibility that `sendWindow` is negative, so adding a check which will help with one of the exceptions captured in https://github.com/libp2p/jvm-libp2p/issues/311 `java.lang.IllegalArgumentException: minimumReadableBytes : -52227 (expected: >= 0)`
Also change to calculate `totalBufferedWrites` on the fly based on the existing `SendBuffer` values in the map. …
> [Yamux] Fix sending of buffered messages after a window update

- README.md
- build.gradle.kts
- libp2p/src/main/kotlin/io/libp2p/core/mux/StreamMuxerProtocol.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxStreamMuxer.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
- libp2p/src/test/kotlin/io/libp2p/security/tls/TlsSecureChannelTest.kt
- Make `maxBufferedConnectionWrites` configurable and default it to 10MiB
- Release and clear  `buffer` when overflowed.
> [Yamux] Increase write buffer size and make it configurable

- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
Based on https://github.com/libp2p/jvm-libp2p/pull/312#issuecomment-1714199823
> [Yamux] Revert merging send and receive windows maps

- libp2p/src/main/kotlin/io/libp2p/core/mux/StreamMuxerProtocol.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
There were some inconsistencies with `sendFrames` method and the send buffer `flush` approach to sending data.
- `sendFrames` was checking if window size is <= 0 and adding to buffer if so and afterwards was slicing the data based on the window size and sending across. So essentially if window size is 10 and data is 100 bytes, it will send across 10 frames of 10 bytes.
- `flush` was respecting the window size and was sending partial data if the length of the data is less than the window size.
I would imagine a better approach is if window size is > 0, just send the whole data respecting the `maxFrameDataLength`. 
- Made `flush` not use `sendFrames` since the data is already limited by `maxFrameDataLength` so no slicing needed
- Renamed `sendFrames` to `sendData`
- Changed `sendData` to …
> [Yamux] Send whole data if window size is > 0

- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
Clear sendBuffers and windowSizes when connection is closed (`channelUnregistered` Netty callback)
> [Yamux] Clear caches when connection is closed

- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
- Send a reset frame when a write buffer has overflown. 
- Ensure we remove entry from `sendWindowSizes` to stop further writes on both FIN and RST
- Close buffer when RST and on `onChildClosed`
- Flush and close buffer on FIN
> [Yamux] Send RST when write buffer has overflowed

- libp2p/src/main/kotlin/io/libp2p/etc/types/ByteArrayExt.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
There could be a race condition case where a frame is being sent before the send buffer has been flushed, which would result in unordered frames. Very hard to replicate in actual test, so wrote a generic test to test order of messages when send buffer is used.
> [Yamux] Don't send frame if send buffer is not empty

- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
There is a tiny possibility the test reaches the test configured `maxBufferedConnectionWrites` (512) if the randomly selected indices are at the end (total bytes sent in this test are 1392), so made it so that 20 indices are selected from every 100 indices in which case the `maxBufferedConnectionWrites`  will never be reached.
> Fix unit test consistency

- libp2p/src/main/kotlin/io/libp2p/etc/util/netty/ByteBufQueue.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/test/kotlin/io/libp2p/etc/util/netty/ByteBufQueueTest.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
* Introduce ByteBufQueue
* Add ByteBufQueue tests
* Writing exec path is always through fill/drain buffer
* Adopt/fix existing tests
* Add new test checking correct handling of negative sendWindowSize
> Refactor YamuxHandler.SendBuffer

- libp2p/src/main/kotlin/io/libp2p/core/mux/StreamMuxerProtocol.kt
- libp2p/src/main/kotlin/io/libp2p/etc/types/AsyncExt.kt
- libp2p/src/main/kotlin/io/libp2p/etc/util/netty/mux/AbstractMuxHandler.kt
- libp2p/src/main/kotlin/io/libp2p/mux/MuxHandler.kt
- libp2p/src/main/kotlin/io/libp2p/mux/MuxerException.kt
- libp2p/src/main/kotlin/io/libp2p/mux/mplex/MplexHandler.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxHandler.kt
- libp2p/src/main/kotlin/io/libp2p/mux/yamux/YamuxStreamMuxer.kt
- libp2p/src/test/kotlin/io/libp2p/mux/yamux/YamuxHandlerTest.kt
https://github.com/libp2p/specs/blob/master/yamux/README.md#ack-backlog--backpressure
Implements `SHOULD at most allow an ACK backlog of 256 streams.`
- Added new parameter `ackBacklogLimit` when initializing Yamux
- Introduced notion of `acknowledged` when initializing yamux stream
- throw and don't create new stream if more than 256 streams are not acknowledged
> [Yamux] Allow max ACK backlog of 256 streams

- libp2p/src/main/kotlin/io/libp2p/transport/tcp/TcpTransport.kt
- libp2p/src/test/kotlin/io/libp2p/transport/tcp/TcpTransportTest.kt
These should mainly be used for bootstrap with a DNS TXT record lookup to expand to list of node multiaddrs
This removes a lot of log spam from failed dial attempts in kademlia
> Don't try and dial DNSADDR addresses

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Updating the new issue templates to use the new YAML configuration system. This makes it similar to the other libp2p implementations and adds links to the technical discussions forum as well as the libp2p community discussions forum.
> chore(cfg): update new issue templates

- README.md
- libp2p/src/main/java/io/libp2p/protocol/autonat/AutonatProtocol.java
- libp2p/src/main/proto/autonat.proto
- libp2p/src/test/java/io/libp2p/core/AutonatTestJava.java
- libp2p/src/test/java/io/libp2p/core/RelayTestJava.java
@Nashatyrev Any thoughts on this?
> Implement autonat protocol

- libp2p/src/main/kotlin/io/libp2p/pubsub/AbstractRouter.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/PubsubRouterTest.kt
Fix returning internal mutable set to avoid ConcurrentModificationException
Might result in the following exception: 
```
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
at io.libp2p.pubsub.PubsubApiImpl.getPeerTopics(PubsubApiImpl.kt:114)
at io.libp2p.pubsub.gossip.Gossip.getPeerTopics(Gossip.kt)
```
> AbstractRouter.getPeerTopics() may throw ConcurrentModificationException

- libp2p/src/main/kotlin/io/libp2p/security/noise/NoiseXXSecureChannel.kt
- libp2p/src/test/java/io/libp2p/core/RelayTestJava.java
- libp2p/src/test/kotlin/io/libp2p/security/CipherSecureChannelTest.kt
Noise negotiator was putting the wrong pubKey into `SecureChannel.Session`: local instead of remote
- Fix the issue
- Add a unit test
> Fix remotePubKey in Noise secure Session

- libp2p/src/main/kotlin/io/libp2p/discovery/MDnsDiscovery.kt
- libp2p/src/test/kotlin/io/libp2p/discovery/MDnsDiscoveryTest.kt
The listen port method was throwing NPE
> Fix mdns when listening with ipv6 wildcard (which includes ipv4)

- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRpcPartsQueue.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipRouterListLimitsTest.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipRpcPartsQueueTest.kt
- libp2p/src/testFixtures/kotlin/io/libp2p/tools/protobuf/RpcBuilder.kt
fixes https://github.com/libp2p/jvm-libp2p/issues/361
> Set topicID on outbound IHAVE and ignore inbound IHAVE for unknown topic

- libp2p/src/main/kotlin/io/libp2p/discovery/MDnsDiscovery.kt
- libp2p/src/test/kotlin/io/libp2p/discovery/MDnsDiscoveryTest.kt
This fixes mdns discovery when using wildcard listen addresses.
It also adds a method to enable adding PeerListener from java (CopyOnWriteList isn't helpful)
Also allow ipv6 only peers
@Nashatyrev
> More mdns fixes

- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
If all peers for a certain topic have sent IDONTWANT for a messageId, then when we publish it outbound, we don't want NoPeersForOutboundMessageException to be thrown
> Don't throw NoPeersForOutboundMessageException if peers DONTWANT message

- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_2Tests.kt
Send IDONTWANT on each publish. Maybe we need to add some filtering to make it more selective, but not sure?
I removed filtering out excluding the `receivedFrom` peer when we are sending IDONTWANT on inbound messages. Think it simplifies the flow and could help in some cases, where `receivedFrom` may send the same message twice.
fixes #383
> Send IDONTWANT prior to publish

- libp2p/src/main/kotlin/io/libp2p/pubsub/PubsubRouter.kt
- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipParams.kt
- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/builders/GossipParamsBuilder.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipPubsubRouterTest.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/SubscriptionsLimitTest.kt
- libp2p/src/testFixtures/kotlin/io/libp2p/pubsub/gossip/Eth2GossipParams.kt
- tools/simulator/src/main/kotlin/io/libp2p/simulate/gossip/Eth2GossipParams.kt
- tools/simulator/src/main/kotlin/io/libp2p/simulate/main/BlobDecouplingSimulation.kt
> [GOSSIP][BREAKING] Replace `floodPublish` param with `floodPublishMaxMessageSizeThreshold` 

- libp2p/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt
- libp2p/src/test/kotlin/io/libp2p/pubsub/gossip/GossipV1_1Tests.kt
> Gossip: direct peers handling fix
